@echo off
echo Initializing Git repository...
git init
echo Adding all files to the staging area...
git add .
echo Committing changes...
git commit -m "first commit"
echo Renaming the default branch to 'main'...
git branch -M main
echo Adding the remote repository...
git remote add origin https://github.com/FueloTech/app_fuelo_style.git
echo Pushing changes to the remote repository...
git push -u origin main
echo Done!
